### ISSUE TITLE
[ GET /jama-oslc-adapter/services/oauth/authorize ] was not original or a wrapper

### ISSUE THREAD

**Issue by andylapping** [OSLC/oslc-adapter-jama#12]
Running through the install and test guide - got to the point where I run the OAuthClient.java and got the request token

Enter this URL in a browser and run again: http://localhost:8080/jama-oslc-adapter/services/oauth/authorize?oauth_token=524cb5ea-7507-47da-b562-07c93b5a41ce

I put that URL  into a web browser and got this:

UT010023: Request HttpServletRequestImpl [ GET /jama-oslc-adapter/services/oauth/authorize ] was not original or a wrapper

**Comment by isccarrasco** [comment]
Hello @skilganon !

Have you tried to add the `allow-non-standard-wrappers="true"` attribute in the `servlet-container` definition on the `standalone.xml` file of your wildfly instance?

This should be like this:
```
<servlet-container name="default" allow-non-standard-wrappers="true">
```

This is described in the 10th step of the `Configuration to enable OAuth (optional)`'s section of the `README` file. 

Regards!

**Comment by andylapping** [comment]
Bingo - totally missed that step - thanks !
