### ISSUE TITLE
Cannot resolve dependency - Latest Commit (101b71e)

### ISSUE THREAD

**Issue by JasonBrownPDX** [OSLC/oslc-adapter-jama#9]
[ERROR] Failed to execute goal on project com.jama.oslc.adapter: Could not resolve dependencies for project com.jama.oslc:com.jama.oslc.adapter:war:1.0-SNAPSHOT: Could not find artifact org.eclipse.lyo.oslc4j.core:oslc4j-jena-provider:jar:2.3.1-SNAPSHOT in lyo-snapshots (https://repo.eclipse.org/content/repositories/lyo-snapshots/) ->

**Comment by berezovskyi** [comment]
I think I said that before somewhere but you are using SNAPSHOT versions at your risk. You should always default to using release versions and go to unreleased versions only if you hit a problem and Lyo devs ask you to.

See https://repo.eclipse.org/content/repositories/lyo-releases/org/eclipse/lyo/oslc4j/core/oslc4j-jena-provider/ for a list of available versions to fix your problem.

**Comment by berezovskyi** [comment]
Welcome to Github, BTW!

**Comment by JasonBrownPDX** [comment]
thanks. I just rebuilt with forced snapshots and it worked fine, then refreshed and saw your msg..

Thanks for the welcome. big learning curve.

**Comment by berezovskyi** [comment]
Note that the given artefacts are in another repo (https://repo.eclipse.org/content/repositories/lyo-releases/)

**Comment by axelreichwein** [comment]
Thanks @JasonBrownPDX  and @berezovskyi for your comments. This latest commit https://github.com/OSLC/oslc-adapter-jama/commit/526693cf20f60ff33435de958fff12d69fff2af3 should provide the fix

**Comment by isccarrasco** [comment]
Hi @JasonBrownPDX and @berezovskyi, you can pull the latest version from master branch, the snapshot versions were removed.
